### ISSUE TITLE
Cant build for SP2019 on premise

### ISSUE THREAD

**Issue by plubber** [tom-daly/spfx-global-navigation#20]
With NODEJS 8..17 cant build...

what to do?

**Comment by tom-daly** [comment]
sp2019 on prem is SPFX v1.4 which requires LTS 6.x or LTS 8.x

are you using node version manager, nvm? please share your specific errors

**Comment by plubber** [comment]
Hi Tom,

I'm explicit using LTS 8.17.0. No I am not using nvm.
I followed the readme step by step for SP2019.

after "npm install" 
.\build.cmd

`SPBuildRig.js:27
            throw new Error(`Your dev environment is running NodeJS version ${process.version} which does` +
            ^

Error: Your dev environment is running NodeJS version v8.17.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=10.13.0 <11.0.0 || >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0
    at SPWebBuildRig.initialize (C:\Users\a-GZSAR0K\Documents\dev\spfx-global-navigation-master\sp2019\node_modules\@microsoft\sp-build-web\lib\SPBuildRig.js:27:19)
    at Object.exports.initialize (C:\Users\a-GZSAR0K\Documents\dev\spfx-global-navigation-master\sp2019\node_modules\@microsoft\sp-build-web\lib\index.js:32:17)
    at Object.<anonymous> (C:\Users\a-GZSAR0K\Documents\dev\spfx-global-navigation-master\sp2019\gulpfile.js:11:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
`

**Comment by plubber** [comment]
yes. it works. thank you very much.
